## Engineering Dates

**Date variables are special type of categorical variable**. By their own nature, date variables will contain a **multitude of different labels**, each one corresponding to a specific date and sometimes time. Date variables, when preprocessed properly **can highly enrich a dataset**. For example, from a date variable we can extract: Week of the year, Month, Quarter, Semester, Year, Day (number),Day of the week, Is Weekend?, Time differences in years, months, days, hrs, etc. **Date variables should not be used as categorical variables when building a machine learning model.** 

In [1]:
import pandas as pd
import numpy as np
import datetime

**Load the dataset with a few selected columns!**

In [2]:
use_cols = ['date_issued', 'date_last_payment']
data = pd.read_csv('loan.csv', usecols=use_cols)
data.head()

date_issued date_last_payment
0  2013-06-11        2016-01-14
1  2014-05-08        2016-01-25
2  2013-10-26        2014-09-26
3  2015-08-20        2016-01-26
4  2014-07-22        2016-01-11

**Parse the dates, currently cast as strings, into datetime format!**

In [3]:
data['issue_dt'] = pd.to_datetime(data['date_issued'])
data['last_pymnt_dt'] = pd.to_datetime(data['date_last_payment'])
data[['date_issued','issue_dt','date_last_payment', 'last_pymnt_dt']].head()

date_issued   issue_dt date_last_payment last_pymnt_dt
0  2013-06-11 2013-06-11        2016-01-14    2016-01-14
1  2014-05-08 2014-05-08        2016-01-25    2016-01-25
2  2013-10-26 2013-10-26        2014-09-26    2014-09-26
3  2015-08-20 2015-08-20        2016-01-26    2016-01-26
4  2014-07-22 2014-07-22        2016-01-11    2016-01-11

### Extract week of the year

**Extract week of year from date, varies from 1 to 52 !**

In [4]:
data['issue_dt_week'] = data['issue_dt'].dt.isocalendar().week
data[['issue_dt', 'issue_dt_week']].head()

issue_dt  issue_dt_week
0 2013-06-11             24
1 2014-05-08             19
2 2013-10-26             43
3 2015-08-20             34
4 2014-07-22             30

In [5]:
data['issue_dt_week'].unique()

<IntegerArray>
[24, 19, 43, 34, 30, 39, 12,  7, 52, 47, 14, 44, 46, 17,  8,  2, 25, 51, 15,
 11, 36, 21, 16, 49, 23,  6, 40, 29, 38, 33, 27, 28, 41, 20, 50,  9,  5, 32,
 45, 10, 42, 48,  4,  1, 26, 13, 37,  3, 22, 35, 18, 31]
Length: 52, dtype: UInt32

### Extract month

**Extract month from date - 1 to 12 !**

In [6]:
data['issue_dt_month'] = data['issue_dt'].dt.month
data[['issue_dt', 'issue_dt_month']].head()

issue_dt  issue_dt_month
0 2013-06-11               6
1 2014-05-08               5
2 2013-10-26              10
3 2015-08-20               8
4 2014-07-22               7

In [7]:
data['issue_dt_month'].unique()

array([ 6,  5, 10,  8,  7,  9,  3,  2, 12, 11,  4,  1], dtype=int64)

### Extract quarter

**Extract quarter from date variable - 1 to 4 !**

In [8]:
data['issue_dt_quarter'] = data['issue_dt'].dt.quarter
data[['issue_dt', 'issue_dt_quarter']].head()

issue_dt  issue_dt_quarter
0 2013-06-11                 2
1 2014-05-08                 2
2 2013-10-26                 4
3 2015-08-20                 3
4 2014-07-22                 3

In [9]:
data['issue_dt_quarter'].unique()

array([2, 4, 3, 1], dtype=int64)

### Extract semester

**Extract semester!**

In [10]:
data['issue_dt_semester'] = np.where(data['issue_dt_quarter'].isin([1,2]), 1, 2)
data.head()

date_issued date_last_payment   issue_dt last_pymnt_dt  issue_dt_week  \
0  2013-06-11        2016-01-14 2013-06-11    2016-01-14             24   
1  2014-05-08        2016-01-25 2014-05-08    2016-01-25             19   
2  2013-10-26        2014-09-26 2013-10-26    2014-09-26             43   
3  2015-08-20        2016-01-26 2015-08-20    2016-01-26             34   
4  2014-07-22        2016-01-11 2014-07-22    2016-01-11             30   

   issue_dt_month  issue_dt_quarter  issue_dt_semester  
0               6                 2                  1  
1               5                 2                  1  
2              10                 4                  2  
3               8                 3                  2  
4               7                 3                  2

In [11]:
data['issue_dt_semester'].unique()

array([1, 2])

###  Extract year

In [12]:
data['issue_dt_year'] = data['issue_dt'].dt.year
data[['issue_dt', 'issue_dt_year']].head()

issue_dt  issue_dt_year
0 2013-06-11           2013
1 2014-05-08           2014
2 2013-10-26           2013
3 2015-08-20           2015
4 2014-07-22           2014

In [13]:
data['issue_dt_year'].unique()

array([2013, 2014, 2015, 2011, 2009, 2012, 2010, 2008, 2007], dtype=int64)

### Extract days, in various formats

**day - numeric from 1-31 !**

In [14]:
data['issue_dt_day'] = data['issue_dt'].dt.day
data[['issue_dt', 'issue_dt_day']].head()

issue_dt  issue_dt_day
0 2013-06-11            11
1 2014-05-08             8
2 2013-10-26            26
3 2015-08-20            20
4 2014-07-22            22

In [15]:
data['issue_dt_day'].unique()

array([11,  8, 26, 20, 22, 21, 27, 14, 25,  4, 13, 23, 19, 18, 24, 17,  6,
        1, 12, 10,  5,  3,  7,  2,  9, 16, 15], dtype=int64)

**Day of the week - from 0 to 6 !**

In [16]:
data['issue_dt_dayofweek'] = data['issue_dt'].dt.dayofweek
data[['issue_dt', 'issue_dt_dayofweek']].head()

issue_dt  issue_dt_dayofweek
0 2013-06-11                   1
1 2014-05-08                   3
2 2013-10-26                   5
3 2015-08-20                   3
4 2014-07-22                   1

In [17]:
data['issue_dt_dayofweek'].unique()

array([1, 3, 5, 2, 6, 4, 0], dtype=int64)

**Day of the week - name!**

In [18]:
data['issue_dt_dayofweek'] = data['issue_dt'].dt.day_name()
data[['issue_dt', 'issue_dt_dayofweek']].head()

issue_dt issue_dt_dayofweek
0 2013-06-11            Tuesday
1 2014-05-08           Thursday
2 2013-10-26           Saturday
3 2015-08-20           Thursday
4 2014-07-22            Tuesday

In [19]:
data['issue_dt_dayofweek'].unique()

array(['Tuesday', 'Thursday', 'Saturday', 'Wednesday', 'Sunday', 'Friday',
       'Monday'], dtype=object)

**Was the application done on the weekend?**

In [20]:
data['issue_dt_is_weekend'] = np.where(data['issue_dt_dayofweek'].isin(['Sunday', 'Saturday']), 1,0)
data[['issue_dt', 'issue_dt_dayofweek','issue_dt_is_weekend']].head()

issue_dt issue_dt_dayofweek  issue_dt_is_weekend
0 2013-06-11            Tuesday                    0
1 2014-05-08           Thursday                    0
2 2013-10-26           Saturday                    1
3 2015-08-20           Thursday                    0
4 2014-07-22            Tuesday                    0

In [21]:
data['issue_dt_is_weekend'].unique()

array([0, 1])

### Extract Time elapsed between dates

**Perhaps more interestingly, extract the date difference between 2 dates!**

In [22]:
data['issue_dt'] - data['last_pymnt_dt']

0      -947 days
1      -627 days
2      -335 days
3      -159 days
4      -538 days
          ...   
9995   -293 days
9996   -312 days
9997   -253 days
9998   -404 days
9999   -362 days
Length: 10000, dtype: timedelta64[ns]

**Same as above capturing just the time difference!**

In [23]:
(data['last_pymnt_dt'] - data['issue_dt']).dt.days.head()

0    947
1    627
2    335
3    159
4    538
dtype: int64

**Calculate number of months passed between 2 dates!**

In [24]:
data['months_passed'] = (data['last_pymnt_dt'] - data['issue_dt']) / np.timedelta64(1, 'M')
data['months_passed'] = np.round(data['months_passed'],0)
data[['last_pymnt_dt', 'issue_dt','months_passed']].head()

last_pymnt_dt   issue_dt  months_passed
0    2016-01-14 2013-06-11           31.0
1    2016-01-25 2014-05-08           21.0
2    2014-09-26 2013-10-26           11.0
3    2016-01-26 2015-08-20            5.0
4    2016-01-11 2014-07-22           18.0

**Or the time difference to today!**

In [25]:
(datetime.datetime.today() - data['issue_dt']).head()

0   3160 days 12:38:38.525554
1   2829 days 12:38:38.525554
2   3023 days 12:38:38.525554
3   2360 days 12:38:38.525554
4   2754 days 12:38:38.525554
Name: issue_dt, dtype: timedelta64[ns]

In [26]:
(datetime.datetime.today() - data['issue_dt']).unique()

array([273069519000352000, 244471119000352000, 261232719000352000, ...,
       361543119000352000, 400077519000352000, 380551119000352000],
      dtype='timedelta64[ns]')