# **Pandas - DataFrames!**

#### **Claurusway Lesson Repeats.. Thanks to our teacher Pat Parton...**

**Create a DataFrame!**

In [363]:
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

In [364]:
pd.DataFrame(data)

0      1
0  terry  quinn

In [365]:
pd.DataFrame(data, columns = ['first_col', 'second_col'])

first_col second_col
0     terry      quinn

**M**

In [366]:
data2 = np.arange(1,10).reshape(3,3)
data2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**M**

In [367]:
pd.DataFrame(data2, columns = ['var1','var2','var3'])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [368]:
data3 = np.arange(1,101).reshape(25, 4)
data3

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16],
       [ 17,  18,  19,  20],
       [ 21,  22,  23,  24],
       [ 25,  26,  27,  28],
       [ 29,  30,  31,  32],
       [ 33,  34,  35,  36],
       [ 37,  38,  39,  40],
       [ 41,  42,  43,  44],
       [ 45,  46,  47,  48],
       [ 49,  50,  51,  52],
       [ 53,  54,  55,  56],
       [ 57,  58,  59,  60],
       [ 61,  62,  63,  64],
       [ 65,  66,  67,  68],
       [ 69,  70,  71,  72],
       [ 73,  74,  75,  76],
       [ 77,  78,  79,  80],
       [ 81,  82,  83,  84],
       [ 85,  86,  87,  88],
       [ 89,  90,  91,  92],
       [ 93,  94,  95,  96],
       [ 97,  98,  99, 100]])

In [369]:
df3 = pd.DataFrame(data3, columns = ['var1','var2','var3','var4'])
df3  

var1  var2  var3  var4
0      1     2     3     4
1      5     6     7     8
2      9    10    11    12
3     13    14    15    16
4     17    18    19    20
5     21    22    23    24
6     25    26    27    28
7     29    30    31    32
8     33    34    35    36
9     37    38    39    40
10    41    42    43    44
11    45    46    47    48
12    49    50    51    52
13    53    54    55    56
14    57    58    59    60
15    61    62    63    64
16    65    66    67    68
17    69    70    71    72
18    73    74    75    76
19    77    78    79    80
20    81    82    83    84
21    85    86    87    88
22    89    90    91    92
23    93    94    95    96
24    97    98    99   100

**M**

In [370]:
df3.head()

var1  var2  var3  var4
0     1     2     3     4
1     5     6     7     8
2     9    10    11    12
3    13    14    15    16
4    17    18    19    20

In [371]:
df3.tail()  

var1  var2  var3  var4
20    81    82    83    84
21    85    86    87    88
22    89    90    91    92
23    93    94    95    96
24    97    98    99   100

In [372]:
df3.tail(3) 

var1  var2  var3  var4
22    89    90    91    92
23    93    94    95    96
24    97    98    99   100

In [373]:
df3.sample(frac=.25)  

var1  var2  var3  var4
21    85    86    87    88
2      9    10    11    12
3     13    14    15    16
24    97    98    99   100
6     25    26    27    28
14    57    58    59    60

In [374]:
df3.sample(n=2)

var1  var2  var3  var4
5     21    22    23    24
21    85    86    87    88

In [375]:
df3.columns

Index(['var1', 'var2', 'var3', 'var4'], dtype='object')

In [376]:
type(df3.columns)

pandas.core.indexes.base.Index

In [377]:
for _ in df3.columns:
    print(_)

var1
var2
var3
var4


In [378]:
df3[['var1','var2']]

var1  var2
0      1     2
1      5     6
2      9    10
3     13    14
4     17    18
5     21    22
6     25    26
7     29    30
8     33    34
9     37    38
10    41    42
11    45    46
12    49    50
13    53    54
14    57    58
15    61    62
16    65    66
17    69    70
18    73    74
19    77    78
20    81    82
21    85    86
22    89    90
23    93    94
24    97    98

In [379]:
df3.columns = ['newcol1', 'newcol2', 'newcol3', 'newcol4']
df3

newcol1  newcol2  newcol3  newcol4
0         1        2        3        4
1         5        6        7        8
2         9       10       11       12
3        13       14       15       16
4        17       18       19       20
5        21       22       23       24
6        25       26       27       28
7        29       30       31       32
8        33       34       35       36
9        37       38       39       40
10       41       42       43       44
11       45       46       47       48
12       49       50       51       52
13       53       54       55       56
14       57       58       59       60
15       61       62       63       64
16       65       66       67       68
17       69       70       71       72
18       73       74       75       76
19       77       78       79       80
20       81       82       83       84
21       85       86       87       88
22       89       90       91       92
23       93       94       95       96
24       97       98       99      100

In [380]:
df3.shape

(25, 4)

In [381]:
df3.ndim

2

In [382]:
df3.size

100

In [383]:
#PanDaS   Panel = 3d

**First copy df3 result above, then use the code below!**

In [384]:
pd.read_clipboard()

newcol2   newcol3   newcol4
   newcol1                              
0  1                2         3        4
1  5                6         7        8
2  9               10        11       12
3  13              14        15       16
4  17              18        19       20
5  21              22        23       24
6  25              26        27       28
7  29              30        31       32
8  33              34        35       36
9  37              38        39       40
10 41              42        43       44
11 45              46        47       48
12 49              50        51       52
13 53              54        55       56
14 57              58        59       60
15 61              62        63       64
16 65              66        67       68
17 69              70        71       72
18 73              74        75       76
19 77              78        79       80
20 81              82        83       84
21 85              86        87       88
22 89              90        91       92
23 93              94        95       96
24 97              98        99      100

In [385]:
for elem in dir(pd):
    if elem.startswith('read'):
        print(elem)

read_clipboard
read_csv
read_excel
read_feather
read_fwf
read_gbq
read_hdf
read_html
read_json
read_orc
read_parquet
read_pickle
read_sas
read_spss
read_sql
read_sql_query
read_sql_table
read_stata
read_table
read_xml


In [386]:
with open('data.csv', 'w') as fh:
    fh.write('1,2,3')

In [265]:
df = pd.read_csv('data.csv')
df

Empty DataFrame
Columns: [1, 2, 3]
Index: []

In [266]:
help(pd.read_csv)

Help on function read_csv in module pandas.io.parsers.readers:

read_csv(filepath_or_buffer: 'FilePathOrBuffer', sep=<no_default>, delimiter=None, header='infer', names=<no_default>, index_col=None, usecols=None, squeeze=False, prefix=<no_default>, mangle_dupe_cols=True, dtype: 'DtypeArg | None' = None, engine=None, converters=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, skipfooter=0, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=False, skip_blank_lines=True, parse_dates=False, infer_datetime_format=False, keep_date_col=False, date_parser=None, dayfirst=False, cache_dates=True, iterator=False, chunksize=None, compression='infer', thousands=None, decimal: 'str' = '.', lineterminator=None, quotechar='"', quoting=0, doublequote=True, escapechar=None, comment=None, encoding=None, encoding_errors: 'str | None' = 'strict', dialect=None, error_bad_lines=None, warn_bad_lines=None, on_bad_lines=None, delim_whitespace=False, low_me

**Insert index and column names!**

In [163]:
import numpy as np
import pandas as pd

In [164]:
data = np.array([1, 2, 5, 6])
data 

array([1, 2, 5, 6])

In [165]:
pd.DataFrame(data=data,
             columns=['coll'],
             index=['a', 'b', 'c', 'd']
             )

coll
a     1
b     2
c     5
d     6

**Insert them after creating a data frame by arange()!**

In [166]:
pd.DataFrame(np.arange(1,24,2).reshape(3,4))

0   1   2   3
0   1   3   5   7
1   9  11  13  15
2  17  19  21  23

In [167]:
df = pd.DataFrame(np.arange(1,24,2).reshape(3,4),
             columns = ['var1', 'var2', 'var3', 'var4']
             )
df 

var1  var2  var3  var4
0     1     3     5     7
1     9    11    13    15
2    17    19    21    23

In [168]:
df.head()

var1  var2  var3  var4
0     1     3     5     7
1     9    11    13    15
2    17    19    21    23

In [169]:
df.tail(2)

var1  var2  var3  var4
1     9    11    13    15
2    17    19    21    23

In [170]:
df.sample(n=3)

var1  var2  var3  var4
2    17    19    21    23
1     9    11    13    15
0     1     3     5     7

In [171]:
df.sample()

var1  var2  var3  var4
0     1     3     5     7

In [172]:
df.index 

RangeIndex(start=0, stop=3, step=1)

In [173]:
df.columns 

Index(['var1', 'var2', 'var3', 'var4'], dtype='object')

In [174]:
for i in df.columns:
    print(i)

var1
var2
var3
var4


In [175]:
print(*df.columns)

var1 var2 var3 var4


**Change column names!**

In [176]:
df.columns = (33,44,55,66)
df

33  44  55  66
0   1   3   5   7
1   9  11  13  15
2  17  19  21  23

In [177]:
df.shape

(3, 4)

In [178]:
df.ndim

2

In [179]:
df.size

12

In [180]:
type(df)

pandas.core.frame.DataFrame

In [146]:
df[33]

0     1
1     9
2    17
Name: 33, dtype: int32

In [147]:
type(df[33])

pandas.core.series.Series

In [181]:
type(df[33].values)

numpy.ndarray

In [182]:
type(df.columns)

pandas.core.indexes.numeric.Int64Index

**Create arrays by randint, then dictionary, then DataFrame**

In [183]:
type(df.columns.values)

numpy.ndarray

In [186]:
s2

array([8, 7, 9, 5])

In [187]:
s3

array([14, 13, 14,  9])

In [188]:
my_dict = {'var1': s1, 'var2': s2, 'var3': s3}
my_dict 

{'var1': array([9, 2, 7, 8]),
 'var2': array([8, 7, 9, 5]),
 'var3': array([14, 13, 14,  9])}

In [189]:
pd.DataFrame(my_dict)

var1  var2  var3
0     9     8    14
1     2     7    13
2     7     9    14
3     8     5     9

**Create DataFrame from dictionary!**

In [190]:
pd.DataFrame(
    data = {'quinn': np.random.randint(2,10, size=2),
            'pat': np.ones((2,)),
            'mike': np.zeros((2,))},
    index=['red', 'blue'],
    dtype=np.int16)

quinn  pat  mike
red       3    1     0
blue      3    1     0

**Create a DataFrame from csv file!**

In [191]:
df = pd.read_csv('C:\\Users\\husey\\Desktop\\python\\src\\ornekcsv.csv')
df

a;b;c
0    78;12;1
1    78;12;2
2   78;324;3
3      7;2;4
4    88;23;5
5       6;2;
6    56;11;6
7     7;12;7
8    56;21;7
9    346;2;8
10     5;1;8
11  456;21;8
12   3;12;88

In [192]:
df = pd.read_csv('C:\\Users\\husey\\Desktop\\python\\src\\ornekcsv.csv', delimiter=';')
df.head()

a    b    c
0  78   12  1.0
1  78   12  2.0
2  78  324  3.0
3   7    2  4.0
4  88   23  5.0

In [193]:
df[1:3]

a    b    c
1  78   12  2.0
2  78  324  3.0

In [194]:
df1 = pd.DataFrame(my_dict)
df1

var1  var2  var3
0     9     8    14
1     2     7    13
2     7     9    14
3     8     5     9

**Change index names and reach them!**

In [195]:
df1.index = ['a', 'b', 'c', 'd']
df1

var1  var2  var3
a     9     8    14
b     2     7    13
c     7     9    14
d     8     5     9

In [196]:
df1['a': 'c']

var1  var2  var3
a     9     8    14
b     2     7    13
c     7     9    14

In [197]:
'var1' in df1

True

In [198]:
'a' in df1.index

True

In [199]:
df

a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

**Is this phrase present in DataFrame?**

In [200]:
df.isin([5])

a      b      c
0   False  False  False
1   False  False  False
2   False  False  False
3   False  False  False
4   False  False   True
5   False  False  False
6   False  False  False
7   False  False  False
8   False  False  False
9   False  False  False
10   True  False  False
11  False  False  False
12  False  False  False

In [201]:
df.isin([5,6,7])

a      b      c
0   False  False  False
1   False  False  False
2   False  False  False
3    True  False  False
4   False  False   True
5    True  False  False
6   False  False   True
7    True  False   True
8   False  False   True
9   False  False  False
10   True  False  False
11  False  False  False
12  False  False  False

**Create arrays by random.randn()!**

In [202]:
from numpy.random import randn
np.random.seed(100)

In [203]:
np.random.rand()

0.5434049417909654

In [204]:
np.random.rand()

0.27836938509379616

In [205]:
np.random.rand(10)

array([0.42451759, 0.84477613, 0.00471886, 0.12156912, 0.67074908,
       0.82585276, 0.13670659, 0.57509333, 0.89132195, 0.20920212])

In [206]:
np.random.rand(5,5)

array([[0.18532822, 0.10837689, 0.21969749, 0.97862378, 0.81168315],
       [0.17194101, 0.81622475, 0.27407375, 0.43170418, 0.94002982],
       [0.81764938, 0.33611195, 0.17541045, 0.37283205, 0.00568851],
       [0.25242635, 0.79566251, 0.01525497, 0.59884338, 0.60380454],
       [0.10514769, 0.38194344, 0.03647606, 0.89041156, 0.98092086]])

In [207]:
np.random.seed(100)

In [208]:
np.random.rand()

0.5434049417909654

In [209]:
np.random.rand()

0.27836938509379616

In [210]:
np.random.seed(100)

**Create a Dataframe with index and column names and reach elements!**

In [211]:
df3 = pd.DataFrame(randn(5,4), 
                   index = 'A B C D E'.split(), 
                   columns = 'W V Y Z'.split()
                   )
df3

W         V         Y         Z
A -1.749765  0.342680  1.153036 -0.252436
B  0.981321  0.514219  0.221180 -1.070043
C -0.189496  0.255001 -0.458027  0.435163
D -0.583595  0.816847  0.672721 -0.104411
E -0.531280  1.029733 -0.438136 -1.118318

In [212]:
np.random.seed(1)

In [213]:
df3 = pd.DataFrame(randn(5,4), 
                   'a b c d e'.split(), 
                   'w x y z'.split()
                   )
df3

w         x         y         z
a  1.624345 -0.611756 -0.528172 -1.072969
b  0.865408 -2.301539  1.744812 -0.761207
c  0.319039 -0.249370  1.462108 -2.060141
d -0.322417 -0.384054  1.133769 -1.099891
e -0.172428 -0.877858  0.042214  0.582815

In [273]:
df3 = pd.DataFrame(randn(5,4), 
                    index = 'a b c d e'.split(), 
                    columns = 'w x y z'.split()
                   )
df3

w         x         y         z
a -0.754398  1.252868  0.512930 -0.298093
b  0.488518 -0.075572  1.131629  1.519817
c  2.185575 -1.396496 -1.444114 -0.504466
d  0.160037  0.876169  0.315635 -2.022201
e -0.306204  0.827975  0.230095  0.762011

In [274]:
df3['y']

a    0.512930
b    1.131629
c   -1.444114
d    0.315635
e    0.230095
Name: y, dtype: float64

In [275]:
df3['y'][1]

1.131629387451427

In [276]:
type(df3['y'])

pandas.core.series.Series

In [277]:
df3[['y']]

y
a  0.512930
b  1.131629
c -1.444114
d  0.315635
e  0.230095

In [278]:
type(df3[['y']])

pandas.core.frame.DataFrame

In [279]:
df3[['y','x']]

y         x
a  0.512930  1.252868
b  1.131629 -0.075572
c -1.444114 -1.396496
d  0.315635  0.876169
e  0.230095  0.827975

In [280]:
type(df3[['y','x']])

pandas.core.frame.DataFrame

In [281]:
df3.z

a   -0.298093
b    1.519817
c   -0.504466
d   -2.022201
e    0.762011
Name: z, dtype: float64

In [282]:
df3.y

a    0.512930
b    1.131629
c   -1.444114
d    0.315635
e    0.230095
Name: y, dtype: float64

In [283]:
df3['a':'c']

w         x         y         z
a -0.754398  1.252868  0.512930 -0.298093
b  0.488518 -0.075572  1.131629  1.519817
c  2.185575 -1.396496 -1.444114 -0.504466

In [284]:
df3['w':'y']

Empty DataFrame
Columns: [w, x, y, z]
Index: []

**Copy DataFrame!**

In [285]:
x = df3.copy()

In [286]:
x.columns = ['A B C D'.split()]
x

A         B         C         D
a -0.754398  1.252868  0.512930 -0.298093
b  0.488518 -0.075572  1.131629  1.519817
c  2.185575 -1.396496 -1.444114 -0.504466
d  0.160037  0.876169  0.315635 -2.022201
e -0.306204  0.827975  0.230095  0.762011

In [287]:
x['a':'c']

A         B         C         D
a -0.754398  1.252868  0.512930 -0.298093
b  0.488518 -0.075572  1.131629  1.519817
c  2.185575 -1.396496 -1.444114 -0.504466

In [288]:
df3

w         x         y         z
a -0.754398  1.252868  0.512930 -0.298093
b  0.488518 -0.075572  1.131629  1.519817
c  2.185575 -1.396496 -1.444114 -0.504466
d  0.160037  0.876169  0.315635 -2.022201
e -0.306204  0.827975  0.230095  0.762011

**Insert a new column!**

In [289]:
df3['x*y'] = df3['x'] * df3['y']
df3

w         x         y         z       x*y
a -0.754398  1.252868  0.512930 -0.298093  0.642633
b  0.488518 -0.075572  1.131629  1.519817 -0.085519
c  2.185575 -1.396496 -1.444114 -0.504466  2.016700
d  0.160037  0.876169  0.315635 -2.022201  0.276550
e -0.306204  0.827975  0.230095  0.762011  0.190513

In [290]:
df3['xxx'] = 1
df3

w         x         y         z       x*y  xxx
a -0.754398  1.252868  0.512930 -0.298093  0.642633    1
b  0.488518 -0.075572  1.131629  1.519817 -0.085519    1
c  2.185575 -1.396496 -1.444114 -0.504466  2.016700    1
d  0.160037  0.876169  0.315635 -2.022201  0.276550    1
e -0.306204  0.827975  0.230095  0.762011  0.190513    1

**Drop columns permanently by inplace=True!**

In [291]:
df3.drop(['x*y', 'xxx'], axis=1, inplace=True)
df3

w         x         y         z
a -0.754398  1.252868  0.512930 -0.298093
b  0.488518 -0.075572  1.131629  1.519817
c  2.185575 -1.396496 -1.444114 -0.504466
d  0.160037  0.876169  0.315635 -2.022201
e -0.306204  0.827975  0.230095  0.762011

### **.loc[] and .iloc[] and their use!**

In [292]:
pd.DataFrame().iloc

**Create a DataFrame by randint() and insert columns!**

In [293]:
m = np.random.randint(1,40, size=[8,4])
m

array([[33, 26, 22, 33],
       [20, 26, 15, 14],
       [21,  7, 14, 16],
       [25, 10,  3,  8],
       [ 6, 37, 38, 22],
       [14, 28, 14, 15],
       [24, 17, 29,  4],
       [ 3, 15,  1, 30]])

In [294]:
df4 = pd.DataFrame(m, columns= ['var1', 'var2', 'var3','var4'])
df4

var1  var2  var3  var4
0    33    26    22    33
1    20    26    15    14
2    21     7    14    16
3    25    10     3     8
4     6    37    38    22
5    14    28    14    15
6    24    17    29     4
7     3    15     1    30

In [295]:
df4.head(2)

var1  var2  var3  var4
0    33    26    22    33
1    20    26    15    14

In [296]:
df4.loc[1]

var1    20
var2    26
var3    15
var4    14
Name: 1, dtype: int32

**Attention: loc contains 5.index, but iloc does not!**

In [297]:
df4.loc[2:5]

var1  var2  var3  var4
2    21     7    14    16
3    25    10     3     8
4     6    37    38    22
5    14    28    14    15

In [298]:
df4.iloc[2:5]

var1  var2  var3  var4
2    21     7    14    16
3    25    10     3     8
4     6    37    38    22

In [299]:
df4.index = 'a b c d e f g h'.split()
df4

var1  var2  var3  var4
a    33    26    22    33
b    20    26    15    14
c    21     7    14    16
d    25    10     3     8
e     6    37    38    22
f    14    28    14    15
g    24    17    29     4
h     3    15     1    30

In [300]:
df4.loc['d':'g']

var1  var2  var3  var4
d    25    10     3     8
e     6    37    38    22
f    14    28    14    15
g    24    17    29     4

In [301]:
df4.loc['d':'g', 'var3']

d     3
e    38
f    14
g    29
Name: var3, dtype: int32

**reach columns in DataFrames!**

In [302]:
df4.loc[:] [['var3']]

var3
a    22
b    15
c    14
d     3
e    38
f    14
g    29
h     1

In [303]:
df4.loc['d':'g'] [['var3']]

var3
d     3
e    38
f    14
g    29

#### **df4.iloc(2:5, 2) ------------->  SyntaxError: invalid syntax**

In [304]:
df4

var1  var2  var3  var4
a    33    26    22    33
b    20    26    15    14
c    21     7    14    16
d    25    10     3     8
e     6    37    38    22
f    14    28    14    15
g    24    17    29     4
h     3    15     1    30

In [305]:
df3.loc['a']

w   -0.754398
x    1.252868
y    0.512930
z   -0.298093
Name: a, dtype: float64

#### **df3 ['a'] -------------->  KeyError: 'a'**

#### **df3.loc['x'] ---------------> KeyError: 'x'**

In [306]:
df3.loc['a', :]

w   -0.754398
x    1.252868
y    0.512930
z   -0.298093
Name: a, dtype: float64

In [307]:
df3.loc[:, 'x']

a    1.252868
b   -0.075572
c   -1.396496
d    0.876169
e    0.827975
Name: x, dtype: float64

In [308]:
df3.iloc[0, :]

w   -0.754398
x    1.252868
y    0.512930
z   -0.298093
Name: a, dtype: float64

#### **df3.loc[:, 0]  ----------->  Keyerror: 0**

**This modul explains python's principles!**

In [309]:
import this

In [310]:
df3.iloc[:, [2]]

y
a  0.512930
b  1.131629
c -1.444114
d  0.315635
e  0.230095

In [311]:
df3

w         x         y         z
a -0.754398  1.252868  0.512930 -0.298093
b  0.488518 -0.075572  1.131629  1.519817
c  2.185575 -1.396496 -1.444114 -0.504466
d  0.160037  0.876169  0.315635 -2.022201
e -0.306204  0.827975  0.230095  0.762011

In [312]:
df3.loc[['a', 'd']]

w         x         y         z
a -0.754398  1.252868  0.512930 -0.298093
d  0.160037  0.876169  0.315635 -2.022201

In [313]:
df3.iloc[0, 1]

1.2528681552332879

**Filter!**

In [314]:
df3[df3 > .5]

w         x         y         z
a       NaN  1.252868  0.512930       NaN
b       NaN       NaN  1.131629  1.519817
c  2.185575       NaN       NaN       NaN
d       NaN  0.876169       NaN       NaN
e       NaN  0.827975       NaN  0.762011

In [315]:
df3[df3 > .5].isna()

w      x      y      z
a   True  False  False   True
b   True   True  False  False
c  False   True   True   True
d   True  False   True   True
e   True  False   True  False

In [316]:
(df3 > .5)

w      x      y      z
a  False   True   True  False
b  False  False   True   True
c   True  False  False  False
d  False   True  False  False
e  False   True  False   True

In [317]:
df3[df3['z']>.5]

w         x         y         z
b  0.488518 -0.075572  1.131629  1.519817
e -0.306204  0.827975  0.230095  0.762011

In [318]:
df3['z']>.5

a    False
b     True
c    False
d    False
e     True
Name: z, dtype: bool

In [319]:
df3[df3['x']<1]

w         x         y         z
b  0.488518 -0.075572  1.131629  1.519817
c  2.185575 -1.396496 -1.444114 -0.504466
d  0.160037  0.876169  0.315635 -2.022201
e -0.306204  0.827975  0.230095  0.762011

In [320]:
df3[df3['x']<1][['y']]

y
b  1.131629
c -1.444114
d  0.315635
e  0.230095

In [321]:
df3[df3['x']<-1]

w         x         y         z
c  2.185575 -1.396496 -1.444114 -0.504466

In [322]:
df3[df3['x']<-1] [['y', 'z']]

y         z
c -1.444114 -0.504466

In [323]:
df3[df3['y']>0] [['z', 'w', 'y']]

z         w         y
a -0.298093 -0.754398  0.512930
b  1.519817  0.488518  1.131629
d -2.022201  0.160037  0.315635
e  0.762011 -0.306204  0.230095

In [324]:
df3['y']>0

a     True
b     True
c    False
d     True
e     True
Name: y, dtype: bool

In [325]:
df3[df3['y']>0]

w         x         y         z
a -0.754398  1.252868  0.512930 -0.298093
b  0.488518 -0.075572  1.131629  1.519817
d  0.160037  0.876169  0.315635 -2.022201
e -0.306204  0.827975  0.230095  0.762011

In [326]:
df3[df3['y']>0] [['z', 'w', 'y']]

z         w         y
a -0.298093 -0.754398  0.512930
b  1.519817  0.488518  1.131629
d -2.022201  0.160037  0.315635
e  0.762011 -0.306204  0.230095

In [327]:
df3[(df3['w']>0) & (df3['y']<1)]

w         x         y         z
c  2.185575 -1.396496 -1.444114 -0.504466
d  0.160037  0.876169  0.315635 -2.022201

In [328]:
df3['w']>0

a    False
b     True
c     True
d     True
e    False
Name: w, dtype: bool

In [329]:
df3['y']<1

a     True
b    False
c     True
d     True
e     True
Name: y, dtype: bool

#### **Python is lazy!**

In [330]:
a = 0

**It does not read 1/0!**

In [331]:
if a and 1/0:
    print('Hey!')

**It reads now!**

In [332]:
if a or 1/0:
    print('Hey!')      # ZeroDivisionError

ZeroDivisionError: division by zero

In [333]:
df3

w         x         y         z
a -0.754398  1.252868  0.512930 -0.298093
b  0.488518 -0.075572  1.131629  1.519817
c  2.185575 -1.396496 -1.444114 -0.504466
d  0.160037  0.876169  0.315635 -2.022201
e -0.306204  0.827975  0.230095  0.762011

In [334]:
df3.loc[(df3.x > -1), ['x', 'y']]

x         y
a  1.252868  0.512930
b -0.075572  1.131629
d  0.876169  0.315635
e  0.827975  0.230095

In [335]:
df3[df3.x > -1][['x', 'y']]

x         y
a  1.252868  0.512930
b -0.075572  1.131629
d  0.876169  0.315635
e  0.827975  0.230095

**Insert a new index**

In [370]:
df3.index 

RangeIndex(start=0, stop=5, step=1)

In [371]:
df3.reset_index()
df3

index         w         x         y         z newix
0      0 -0.754398  1.252868  0.512930 -0.298093    ca
1      1  0.488518 -0.075572  1.131629  1.519817    ny
2      2  2.185575 -1.396496 -1.444114 -0.504466    or
3      3  0.160037  0.876169  0.315635 -2.022201    co
4      4 -0.306204  0.827975  0.230095  0.762011    nh

In [373]:
df3.reset_index(inplace=True)
df3

level_0  index         w         x         y         z newix
0        0      0 -0.754398  1.252868  0.512930 -0.298093    ca
1        1      1  0.488518 -0.075572  1.131629  1.519817    ny
2        2      2  2.185575 -1.396496 -1.444114 -0.504466    or
3        3      3  0.160037  0.876169  0.315635 -2.022201    co
4        4      4 -0.306204  0.827975  0.230095  0.762011    nh

In [374]:
df3.index = df3['index']
df3

level_0  index         w         x         y         z newix
index                                                              
0            0      0 -0.754398  1.252868  0.512930 -0.298093    ca
1            1      1  0.488518 -0.075572  1.131629  1.519817    ny
2            2      2  2.185575 -1.396496 -1.444114 -0.504466    or
3            3      3  0.160037  0.876169  0.315635 -2.022201    co
4            4      4 -0.306204  0.827975  0.230095  0.762011    nh

**Drop index!**

In [375]:
df3.reset_index(drop=True, inplace=True)
df3

level_0  index         w         x         y         z newix
0        0      0 -0.754398  1.252868  0.512930 -0.298093    ca
1        1      1  0.488518 -0.075572  1.131629  1.519817    ny
2        2      2  2.185575 -1.396496 -1.444114 -0.504466    or
3        3      3  0.160037  0.876169  0.315635 -2.022201    co
4        4      4 -0.306204  0.827975  0.230095  0.762011    nh

In [376]:
df3.drop(['index'], axis=1, inplace =True)
df3 

level_0         w         x         y         z newix
0        0 -0.754398  1.252868  0.512930 -0.298093    ca
1        1  0.488518 -0.075572  1.131629  1.519817    ny
2        2  2.185575 -1.396496 -1.444114 -0.504466    or
3        3  0.160037  0.876169  0.315635 -2.022201    co
4        4 -0.306204  0.827975  0.230095  0.762011    nh

In [377]:
newix = ['ca', 'ny', 'or', 'co', 'nh']

In [378]:
df3['newix'] = newix
df3

level_0         w         x         y         z newix
0        0 -0.754398  1.252868  0.512930 -0.298093    ca
1        1  0.488518 -0.075572  1.131629  1.519817    ny
2        2  2.185575 -1.396496 -1.444114 -0.504466    or
3        3  0.160037  0.876169  0.315635 -2.022201    co
4        4 -0.306204  0.827975  0.230095  0.762011    nh

**Make a column index!**

In [379]:
df3.set_index('newix')  # not inplace = True

level_0         w         x         y         z
newix                                                 
ca           0 -0.754398  1.252868  0.512930 -0.298093
ny           1  0.488518 -0.075572  1.131629  1.519817
or           2  2.185575 -1.396496 -1.444114 -0.504466
co           3  0.160037  0.876169  0.315635 -2.022201
nh           4 -0.306204  0.827975  0.230095  0.762011

**Dictionary and translation!**

In [380]:
translate = {
    'italien': 
        {'dove': 'where',
         'che': 'what',
         'chi': 'who',
         },
    'english':
        {'where': 'dove',
         'what': 'che',
         'who': 'chi'
            
         }
    }

In [381]:
list(translate.keys())

['italien', 'english']

In [382]:
translate['italien']

{'dove': 'where', 'che': 'what', 'chi': 'who'}

In [383]:
translate['italien']['dove']

'where'

**Create multi index by zip()!**

In [350]:
outside = ['M1', 'M1', 'M1', 'M2', 'M2', 'M2', 'M3', 'M3', 'M3']
inside = [1,2,3,4,5,6,7,8,9]
multi_index = list(zip(outside, inside))
multi_index

[('M1', 1),
 ('M1', 2),
 ('M1', 3),
 ('M2', 4),
 ('M2', 5),
 ('M2', 6),
 ('M3', 7),
 ('M3', 8),
 ('M3', 9)]

In [351]:
hier_index = pd.MultiIndex.from_tuples(multi_index)
hier_index

MultiIndex([('M1', 1),
            ('M1', 2),
            ('M1', 3),
            ('M2', 4),
            ('M2', 5),
            ('M2', 6),
            ('M3', 7),
            ('M3', 8),
            ('M3', 9)],
           )

In [352]:
df5 = pd.DataFrame(np.random.randn(9,4),
                   index=hier_index,
                   columns=['A','B','C','D'])
df5 

A         B         C         D
M1 1 -0.592445  0.882003  0.778838  1.499032
   2  1.542909 -0.447732 -1.777692 -1.791835
   3 -1.005065 -0.400376  0.536258  1.299785
M2 4  0.094180 -0.283169 -0.395713 -0.712432
   5 -1.356346 -0.837716 -0.493911 -0.141446
   6 -0.874671  1.046876  0.269837  0.408915
M3 7 -0.337337  0.110747  0.574400  0.686630
   8  1.723770 -2.421971 -1.501183  0.046399
   9 -0.076532  0.842092  0.367400 -0.511294

In [353]:
df5.loc['M3']

A         B         C         D
7 -0.337337  0.110747  0.574400  0.686630
8  1.723770 -2.421971 -1.501183  0.046399
9 -0.076532  0.842092  0.367400 -0.511294

**Reach elements by multi index!**

In [385]:
df5.loc['M2'].loc[[5]]

A         B         C         D
Num                                        
5   -1.356346 -0.837716 -0.493911 -0.141446

In [386]:
df5.loc['M2'].loc[5]

A   -1.356346
B   -0.837716
C   -0.493911
D   -0.141446
Name: 5, dtype: float64

In [387]:
df5.index.names

FrozenList(['Group', 'Num'])

In [388]:
df5.index.names = ['Group', 'Num']
df5 

A         B         C         D
Group Num                                        
M1    1   -0.592445  0.882003  0.778838  1.499032
      2    1.542909 -0.447732 -1.777692 -1.791835
      3   -1.005065 -0.400376  0.536258  1.299785
M2    4    0.094180 -0.283169 -0.395713 -0.712432
      5   -1.356346 -0.837716 -0.493911 -0.141446
      6   -0.874671  1.046876  0.269837  0.408915
M3    7   -0.337337  0.110747  0.574400  0.686630
      8    1.723770 -2.421971 -1.501183  0.046399
      9   -0.076532  0.842092  0.367400 -0.511294

**Reach elements by xs[]**

In [390]:
df5.xs('M1')

A         B         C         D
Num                                        
1   -0.592445  0.882003  0.778838  1.499032
2    1.542909 -0.447732 -1.777692 -1.791835
3   -1.005065 -0.400376  0.536258  1.299785

In [391]:
df5.xs(['M1',2])

C:\Users\husey\AppData\Local\Temp/ipykernel_17396/1597791428.py:1: FutureWarning: Passing lists as key for xs is deprecated and will be removed in a future version. Pass key as a tuple instead.
  df5.xs(['M1',2])


A    1.542909
B   -0.447732
C   -1.777692
D   -1.791835
Name: (M1, 2), dtype: float64

**Null values!**

In [397]:
np.nan # sort of like none

nan

In [398]:
None 

In [399]:
a = None 

In [400]:
a is None  

True

In [401]:
b = np.nan 
b 

nan

In [402]:
t = pd.Series([1,2,3, np.nan])
t 

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [403]:
t.mean()

2.0

In [404]:
np.nan == np.NaN

False