# **Pandas - Series**

## **Claurusway Lesson Repeats.. Thanks to our teacher Pat Parton...**

**Create Series**

In [3]:
import numpy as np
import pandas as pd

In [4]:
np.array([1,3,5])

array([1, 3, 5])

In [5]:
pd.Series([1,3,5])

0    1
1    3
2    5
dtype: int64

In [6]:
ser = pd.Series([1,3,5])
ser.dtype

dtype('int64')

In [7]:
ser.size

3

In [8]:
ser.ndim

1

In [9]:
ser

0    1
1    3
2    5
dtype: int64

In [10]:
type(ser.values)

numpy.ndarray

**Reach the index and values of the Series!**

In [11]:
ser.index

RangeIndex(start=0, stop=3, step=1)

In [12]:
ser.values

array([1, 3, 5], dtype=int64)

In [13]:
for _ in ser.values:
    print(_)

1
3
5


In [14]:
[i for i in ser.values]

[1, 3, 5]

In [15]:
list(ser.values)

[1, 3, 5]

**Convert Series to list!**

In [16]:
ser.to_list()

[1, 3, 5]

**Create Series from list comprehension!**

In [17]:
ser = pd.Series([i for i in range(10)])
ser 

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [18]:
ser.head()

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [19]:
ser.head(3)

0    0
1    1
2    2
dtype: int64

In [20]:
ser.tail()

5    5
6    6
7    7
8    8
9    9
dtype: int64

In [21]:
ser.tail(7)

3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [22]:
ser.sample()

5    5
dtype: int64

In [23]:
ser.sample(n=4)

0    0
6    6
7    7
9    9
dtype: int64

In [24]:
ser.sample(frac=.4)

6    6
5    5
0    0
8    8
dtype: int64

In [25]:
ser.sample(frac=.3).size 

3

**Create Series from list comprehension of a string!**

In [26]:
[i for i in 'clarusway']

['c', 'l', 'a', 'r', 'u', 's', 'w', 'a', 'y']

In [27]:
pd.Series([i for i in 'clarusway'])

0    c
1    l
2    a
3    r
4    u
5    s
6    w
7    a
8    y
dtype: object

**Create Series from list, array and dictionary!**

In [28]:
labels = ['a','b','c','d']
my_list = [10,20,30]
arr = np.array([10,20,30,40])
d = {'a':10,'b':20,'c':30}
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [29]:
pd.Series(data=arr)3

0    10
1    20
2    30
3    40
dtype: int32

In [30]:
pd.Series(data=arr, index=labels)

a    10
b    20
c    30
d    40
dtype: int32

In [31]:
d

{'a': 10, 'b': 20, 'c': 30}

In [33]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [34]:
d

{'a': 10, 'b': 20, 'c': 30}

In [35]:
pd.Series(data=d, index=['q','c','v'])

q     NaN
c    30.0
v     NaN
dtype: float64

In [36]:
myset = {1,2,4}

pd.Series(data=myset)   -->  TypeError: 'set' type is unordered

**When you create an empty list, describe its type. If not it can turn an object!**

In [43]:
pd.Series(list(), dtype= int)

Series([], dtype: int32)

In [46]:
a = pd.Series([myset, 'x', 33], index = ['x','y','z'])
a

x    {1, 2, 4}
y            x
z           33
dtype: object

In [47]:
a[0]

{1, 2, 4}

**Change index!**

In [48]:
a.index = ['set','str','print']
a

set      {1, 2, 4}
str              x
print           33
dtype: object

**Sorting Series!**

In [49]:
ser1 =  pd.Series([1,2,3,4], index = ['USA','Germany','USSR', 'Japan'])     
ser2 =  pd.Series([1,2,5,4], index = ['USA','Germany','Italy', 'Japan'])                 
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [50]:
ser1.sort_index(ascending=True)

Germany    2
Japan      4
USA        1
USSR       3
dtype: int64

In [52]:
ser2.sort_values(ascending=True)             
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

**ascending=True is default. False, makes sorting from biggest to smallest!**

In [53]:
ser1.sort_index(ascending=False)   

USSR       3
USA        1
Japan      4
Germany    2
dtype: int64

In [54]:
ser1.sort_index(ascending=False)   

USSR       3
USA        1
Japan      4
Germany    2
dtype: int64

In [55]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [56]:
a = ser1.sort_index(ascending=True)              
a

Germany    2
Japan      4
USA        1
USSR       3
dtype: int64

**Implace=True, makes the changes permenant!**

In [57]:
ser1.sort_index(ascending=True, inplace=True)   
ser1

Germany    2
Japan      4
USA        1
USSR       3
dtype: int64

**Second method for permanent change!**

In [58]:
x = ser1.copy() 

**Reach elements of Series!**

In [70]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [71]:
ser2['Germany':'Italy'] 

Germany    2
Italy      5
dtype: int64

In [72]:
ser2[1:2] 

Germany    2
dtype: int64

In [73]:
ser2[1] 

2

In [74]:
ser1

Germany    2
Japan      4
USA        1
USSR       3
dtype: int64

In [75]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

**Join two Series!**

In [61]:
added = ser1 + ser2
added

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

**Is null present!**

In [62]:
ser1.isnull()

Germany    False
Japan      False
USA        False
USSR       False
dtype: bool

In [63]:
added.isnull()   

Germany    False
Italy       True
Japan      False
USA        False
USSR        True
dtype: bool

In [64]:
ser1.isnull().any() 

False

In [65]:
added.isnull().all()  

False

In [66]:
pd.NaT  #sort like NaN   

NaT

In [67]:
a = np.array([1,2,33,444,75])
panser = pd.Series(a)
panser

0      1
1      2
2     33
3    444
4     75
dtype: int32

In [68]:
panser[3]

444

In [69]:
panser[0:1]

0    1
dtype: int32

In [70]:
panser.index

RangeIndex(start=0, stop=5, step=1)

**Change indexes and reach values!**

In [71]:
panser.index = ['terry', 'michael', 'orion', 'jason', 'quinn']    
panser 

terry        1
michael      2
orion       33
jason      444
quinn       75
dtype: int32

In [72]:
panser['quinn']        # loc

75

In [73]:
panser[4]          # iloc

75

In [74]:
ix = [ 'michael', 'terry', 'jason']              
ix 

['michael', 'terry', 'jason']

In [75]:
d  

{'a': 10, 'b': 20, 'c': 30}

In [76]:
pd.Series(d, index=['a']) 

a    10
dtype: int64

In [77]:
panser[ix]              
panser

terry        1
michael      2
orion       33
jason      444
quinn       75
dtype: int32

In [78]:
panser['terry': 'quinn'] 

terry        1
michael      2
orion       33
jason      444
quinn       75
dtype: int32

In [79]:
panser.keys   

<bound method Series.keys of terry        1
michael      2
orion       33
jason      444
quinn       75
dtype: int32>

In [80]:
panser.keys()  

Index(['terry', 'michael', 'orion', 'jason', 'quinn'], dtype='object')

In [81]:
panser.index 

Index(['terry', 'michael', 'orion', 'jason', 'quinn'], dtype='object')

In [82]:
panser.values    

array([  1,   2,  33, 444,  75])

In [83]:
panser.items   

<bound method Series.items of terry        1
michael      2
orion       33
jason      444
quinn       75
dtype: int32>

In [84]:
panser.items() 

In [85]:
for index_value, num_value in panser.items():
    print(index_value, num_value) 
d

terry 1
michael 2
orion 33
jason 444
quinn 75


{'a': 10, 'b': 20, 'c': 30}

In [86]:
'a' in d

True

In [87]:
'quin' in panser

False

In [88]:
'Trump' in panser

False

In [89]:
panser

terry        1
michael      2
orion       33
jason      444
quinn       75
dtype: int32

**isin  ----> Is there this value in Series!**

In [93]:
panser.isin([444])

terry      False
michael    False
orion      False
jason       True
quinn      False
dtype: bool

In [94]:
type(panser.isin([444]))

pandas.core.series.Series

In [95]:
panser.isin([444]).all()

False

In [96]:
panser.isin([444]).any()

True

In [97]:
panser.isin([444,75,33])
panser

terry        1
michael      2
orion       33
jason      444
quinn       75
dtype: int32

**Change values!**

In [102]:
panser['terry'] = 666
panser['mychael'] = 1.01
panser

terry        666
michael      2.0
orion       33.0
jason      444.0
quinn       75.0
mychael     1.01
dtype: object

In [103]:
panser['mychael'] = 'aaaa'
panser

terry        666
michael      2.0
orion       33.0
jason      444.0
quinn       75.0
mychael     aaaa
dtype: object

In [104]:
panser['mychael'] = 234
panser

terry        666
michael      2.0
orion       33.0
jason      444.0
quinn       75.0
mychael      234
dtype: object

**Change type!**

In [107]:
panser.astype(int)

terry      666
michael      2
orion       33
jason      444
quinn       75
mychael    234
dtype: int32

**Filter!**

In [110]:
panser[panser>100]

terry        666
jason      444.0
mychael      234
dtype: object

In [111]:
myeval = panser > 100

In [112]:
panser[myeval]

terry        666
jason      444.0
mychael      234
dtype: object

In [113]:
panser * myeval

terry        666
michael      0.0
orion        0.0
jason      444.0
quinn        0.0
mychael      234
dtype: object

In [114]:
data = [['terry', 'quinn']]
data

[['terry', 'quinn']]