# **Numpy Library**

**Claurusway Lessons Repeat... Thanks to our teacher Pat Parton**

# **Part II**

**Reach the array elements!**

In [39]:
arr = np.arange(0,11)
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
arr[8]

8

In [41]:
arr[-1]

10

In [42]:
arr[1:5]

array([1, 2, 3, 4])

In [43]:
arr[1::2]

array([1, 3, 5, 7, 9])

In [44]:
arr[0::2]

array([ 0,  2,  4,  6,  8, 10])

In [45]:
arr[::2]

array([ 0,  2,  4,  6,  8, 10])

**Assign values to elements!**

In [46]:
arr[3] = 333
arr 

array([  0,   1,   2, 333,   4,   5,   6,   7,   8,   9,  10])

In [47]:
arr[:3] = 666
arr

array([666, 666, 666, 333,   4,   5,   6,   7,   8,   9,  10])

In [48]:
lst = [1,2,3]
for _ in range(len(lst)-1):
    lst[_] = 777
lst 

[777, 777, 3]

In [49]:
arr[::] = 888
arr 

array([888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888])

**Copies and real copies in list and array!**

In [50]:
lst = [1,2,3]
lst_copy = lst 
lst[0] = 666
lst 

[666, 2, 3]

In [51]:
lst_copy

[666, 2, 3]

In [52]:
id(lst) == id(lst_copy)

True

In [53]:
arr 

array([888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888])

In [54]:
arr[0]=0
arr 

array([  0, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888])

In [103]:
arr_copy = arr
arr_copy[0]=-999  
arr 

array([-999, -777,  888,  888,  888,  888,  888,  888,  888,  888,  888])

In [104]:
array_copy = arr[:2]
array_copy 

array([-999, -777])

In [105]:
array_copy[1] = -777 
array_copy

array([-999, -777])

In [106]:
arr 

array([-999, -777,  888,  888,  888,  888,  888,  888,  888,  888,  888])

In [107]:
array_copy.base 

array([-999, -777,  888,  888,  888,  888,  888,  888,  888,  888,  888])

In [108]:
id(array_copy.base) == id(arr)

True

In [111]:
true_copy =  arr.copy()

In [112]:
another_true_copy = arr[:]
id(another_true_copy) == id(arr)

False

In [113]:
id(true_copy) == id(arr)

False

**Reach the elements in matrix!**

In [112]:
another_true_copy = arr[:]
id(another_true_copy) == id(arr)

False

In [64]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [65]:
np.arange(5,50,5).reshape(3,3)

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [66]:
arr_2d[0]

array([ 5, 10, 15])

In [67]:
r = arr_2d[1]
type(r)

numpy.ndarray

In [68]:
r[0]

20

In [69]:
type(r[0])

numpy.int32

In [70]:
arr_2d[1][0]

20

In [71]:
arr_2d[1,0]

20

In [72]:
arr_2d[0:2,1:]

array([[10, 15],
       [25, 30]])

In [73]:
arr_2d[:,1]

array([10, 25, 40])

In [74]:
arr_2d[:,:2]

array([[ 5, 10],
       [20, 25],
       [35, 40]])

In [75]:
arr_tiny = np.array([10,20,30], dtype=np.int8)
arr_tiny 

array([10, 20, 30], dtype=int8)

**Smallest numbers has int8 type. It is till 127. If more than 127 gives: -(128-N % 128)**

In [119]:
arr_tiny[1] = 255
arr_tiny 

array([10, -1, 30], dtype=int8)

**Reach elements in matrices!**

In [77]:
arr_2d.dtype 
arr_2d 

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [78]:
arr_2d[0,0] = 666
arr_2d

array([[666,  10,  15],
       [ 20,  25,  30],
       [ 35,  40,  45]])

In [120]:
arr_2d[0,0] = 666.666
arr_2d

array([[666,  10,  15],
       [ 20,  25,  30],
       [ 35,  40,  45]])

In [80]:
v = np.arange(0,30,3)
v 

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [81]:
v[1]

3

In [82]:
v[-1]

27

In [83]:
v[1:3]

array([3, 6])

In [84]:
index_list = [7,3,6]

In [85]:
v[index_list]

array([21,  9, 18])

In [86]:
v[[7,3,6]]

array([21,  9, 18])

In [87]:
arr2d = np.zeros((10,10), dtype=int)
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [88]:
arr2d.dtype 

dtype('int32')

In [89]:
arr2d.shape 

(10, 10)

In [90]:
rows, columns = arr2d.shape 
rows 

10

In [91]:
arr2d[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [92]:
for i in range(rows):
    arr2d[i]=i
arr2d 

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [55]:
arr2d[[3,7,4,3]]

array([[3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [123]:
jj = np.arange(1,17).reshape(4,4)
jj 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [130]:
zip([0,2],[0,1])

In [131]:
[i for i in zip([0,2],[0,1])]

[(0, 0), (2, 1)]

In [124]:
jj[[0,2,3],[0,1,3]]

array([ 1, 10, 16])

In [58]:
jj[0,0], jj[2,1], jj[3,3]

(1, 10, 16)

In [138]:
jj 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [139]:
jj[1, [1,2]]

array([6, 7])

In [140]:
jj[[1,2]]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [141]:
jj[[1,2],1 ]

array([ 6, 10])

In [142]:
jj[:,[1,2]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [143]:
jj[1:3,[1,2]]

array([[ 6,  7],
       [10, 11]])

In [144]:
jj[[1,2],[1,2]]

array([ 6, 11])

In [145]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [146]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [147]:
bool_arr = arr > 4
bool_arr 

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [148]:
arr[[1,2]]

array([2, 3])

In [149]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [150]:
arr[(arr!=3) & (arr!=4)]

array([ 1,  2,  5,  6,  7,  8,  9, 10])

In [151]:
arr[(arr<2) | (arr>8)]

array([ 1,  9, 10])

In [152]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Operations in arrays!**

In [153]:
arr+arr 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [154]:
arr*2 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [155]:
arr-arr 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [158]:
arr/arr 

C:\Users\husey\AppData\Local\Temp/ipykernel_4660/3068588409.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [159]:
import warnings 
warnings.filterwarnings('ignore')

In [160]:
np.nan, np.NaN, np.NAN 

(nan, nan, nan)

In [161]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [162]:
arr-2 

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [163]:
arr%2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [164]:
arr%3

array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0], dtype=int32)

In [165]:
arr*3/10-9

array([-9. , -8.7, -8.4, -8.1, -7.8, -7.5, -7.2, -6.9, -6.6, -6.3])

In [166]:
arr.dtype 

dtype('int32')

In [167]:
a = arr*3/10-9
a.dtype

dtype('float64')

In [168]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [169]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [170]:
np.max(arr)

9

In [171]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [172]:
np.sin(np.pi/2)

1.0

In [173]:
np.sin(np.pi/4)

0.7071067811865476

In [174]:
np.tan(np.pi/4)

0.9999999999999999

In [175]:
np.log(arr)

array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [176]:
np.log10(10)

1.0

In [177]:
np.log10(100)

2.0

In [178]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [179]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [180]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [181]:
np.random.randint(1,1001,50)

array([ 988,  784,  573,  581,  559,  493,  454,  209,  516,  820,   48,
        232,  806,  515,  622,  944,   92,  675,  196,  787,  973,  593,
        932,  702,  147,  353,  522,  648,  467,  977,  795,  787,  749,
         30,  902,  615,  647,  259,   71,  113,  372,  108,  468,  686,
       1000,  978,  686,   10,  940,  202])

**Statistical values in arrays!**

In [182]:
np.mean(v)

13.5

In [183]:
np.median(v)

13.5

In [184]:
arr 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [185]:
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [186]:
d = np.array(((0,1,2,3),(10,11,12,13),(20,21,22,23)))
d 

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

In [187]:
d.max()

23

In [188]:
d.max(axis=0)

array([20, 21, 22, 23])

In [189]:
d.max(axis=1)

array([ 3, 13, 23])

In [190]:
np.std(d,axis=0)

array([8.16496581, 8.16496581, 8.16496581, 8.16496581])

In [191]:
np.std(d,axis=1)

array([1.11803399, 1.11803399, 1.11803399])

In [116]:
np.std(d)

8.241156876717412

In [117]:
from scipy import stats
stats.describe(d)

DescribeResult(nobs=3, minmax=(array([0, 1, 2, 3]), array([20, 21, 22, 23])), mean=array([10., 11., 12., 13.]), variance=array([100., 100., 100., 100.]), skewness=array([0., 0., 0., 0.]), kurtosis=array([-1.5, -1.5, -1.5, -1.5]))

In [118]:
d 

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

In [119]:
a 

array([-9. , -8.7, -8.4, -8.1, -7.8, -7.5, -7.2, -6.9, -6.6, -6.3])

In [120]:
np.corrcoef(d)   # d.corrcoef ==> Error!

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [123]:
d

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

In [124]:
d%2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]], dtype=int32)

In [125]:
d*(d%2)

array([[ 0,  1,  0,  3],
       [ 0, 11,  0, 13],
       [ 0, 21,  0, 23]])

**Masked arrays has missing or invalid entries. Ma module provides replacement for them.**

In [192]:
np.ma 

<module 'numpy.ma' from 'C:\\Users\\husey\\anaconda3\\lib\\site-packages\\numpy\\ma\\__init__.py'>

In [193]:
?np.ma

Type:        module
String form: <module 'numpy.ma' from 'C:\\Users\\husey\\anaconda3\\lib\\site-packages\\numpy\\ma\\__init__.py'>
File:        c:\users\husey\anaconda3\lib\site-packages\numpy\ma\__init__.py
Docstring:  
Masked Arrays

Arrays sometimes contain invalid or missing data.  When doing operations
on such arrays, we wish to suppress invalid values, which is the purpose masked
arrays fulfill (an example of typical use is given below).

For example, examine the following array:

>>> x = np.array([2, 1, 3, np.nan, 5, 2, 3, np.nan])

When we try to calculate the mean of the data, the result is undetermined:

>>> np.mean(x)
nan

The mean is calculated using roughly ``np.sum(x)/len(x)``, but since
any number added to ``NaN`` [1]_ produces ``NaN``, this doesn't work.  Enter
masked arrays:

>>> m = np.ma.masked_array(x, np.isnan(x))
>>> m
masked_array(data = [2.0 1.0 3.0 -- 5.0 2.0 3.0 --],
      mask = [False False False  True False False False  True],
      fill_value=1e+20)

Here

In [194]:
np.ma.masked_array 

numpy.ma.core.MaskedArray

In [197]:
x = np.array([2, 1, 3, np.nan, 5, 2, 3, np.nan])
np.mean(x)

nan

In [198]:
m = np.ma.masked_array(x, np.isnan(x))
m

masked_array(data=[2.0, 1.0, 3.0, --, 5.0, 2.0, 3.0, --],
             mask=[False, False, False,  True, False, False, False,  True],
       fill_value=1e+20)

In [199]:
np.mean(m)

2.6666666666666665

In [200]:
g = np.array([1,np.nan,3])
g 

array([ 1., nan,  3.])

In [201]:
np.ma.masked_array(g, [False,True,True])

masked_array(data=[1.0, --, --],
             mask=[False,  True,  True],
       fill_value=1e+20)

In [203]:
g = np.array([1,np.nan,3]).mean()
g

nan

**Ravel()**

In [207]:
d 

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

In [208]:
e = d.ravel()
e

array([ 0,  1,  2,  3, 10, 11, 12, 13, 20, 21, 22, 23])

In [209]:
len(e)

12

In [210]:
d.flat

In [211]:
?d.flat

Type:            flatiter
String form:     <numpy.flatiter object at 0x0000018E75F4ACF0>
Length:          12
File:            c:\users\husey\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:       <no docstring>
Class docstring:
Flat iterator object to iterate over arrays.

A `flatiter` iterator is returned by ``x.flat`` for any array `x`.
It allows iterating over the array as if it were a 1-D array,
either in a for-loop or by calling its `next` method.

Iteration is done in row-major, C-style order (the last
index varying the fastest). The iterator can also be indexed using
basic slicing or advanced indexing.

See Also
--------
ndarray.flat : Return a flat iterator over an array.
ndarray.flatten : Returns a flattened copy of an array.

Notes
-----
A `flatiter` iterator can not be constructed directly from Python code
by calling the `flatiter` constructor.

Examples
--------
>>> x = np.arange(6).reshape(2, 3)
>>> fl = x.flat
>>> type(fl)
<class 'numpy.flatiter'>
>>> for item in 

In [212]:
it = d.flat

**next()**

In [213]:
next(it)

0

In [214]:
next(it), next(it)

(1, 2)

In [215]:
r = 4
c = len(e)//r
c

3

**reshape(), resize()**

In [216]:
d.reshape(r,c)

array([[ 0,  1,  2],
       [ 3, 10, 11],
       [12, 13, 20],
       [21, 22, 23]])

In [217]:
rs = np.resize(d,(2,2))
rs

array([[0, 1],
       [2, 3]])

In [218]:
np.resize(d,(2,3))

array([[ 0,  1,  2],
       [ 3, 10, 11]])

In [219]:
np.resize(d,(5,5))

array([[ 0,  1,  2,  3, 10],
       [11, 12, 13, 20, 21],
       [22, 23,  0,  1,  2],
       [ 3, 10, 11, 12, 13],
       [20, 21, 22, 23,  0]])

In [220]:
rs_copy = rs 

In [221]:
np.resize(rs_copy,(5,5))

array([[0, 1, 2, 3, 0],
       [1, 2, 3, 0, 1],
       [2, 3, 0, 1, 2],
       [3, 0, 1, 2, 3],
       [0, 1, 2, 3, 0]])

In [222]:
np.resize(rs_copy,(2,3)) # Hata vermedi warnings.setting.warnings sebebiyle!
rs 

array([[0, 1],
       [2, 3]])

In [223]:
x = np.resize(rs,(1,2))
x 

array([[0, 1]])

In [224]:
np.resize(x,(3,3))

array([[0, 1, 0],
       [1, 0, 1],
       [0, 1, 0]])

**fromiter()**

In [226]:
np.fromiter

<function numpy.fromiter>

In [227]:
np.fromiter([i for i in range(1000)], dtype=int)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [228]:
np.fromiter((range(1000)), dtype=int)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [229]:
np.fromiter((range(1000)), dtype=int).reshape(10,10,10)

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
        [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
        [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
        [160, 161, 162, 163, 164, 165,

In [230]:
np.fromiter((3,2,5), dtype=int)

array([3, 2, 5])

In [231]:
rs.flat 

In [232]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [233]:
a[0:3]

array([20, 21, 22])

In [234]:
a[:3]

array([20, 21, 22])

In [235]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [236]:
a[1::2]

array([21, 23, 25, 27, 29])

In [237]:
a2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [238]:
a2[2,1]

8

In [239]:
a2[:,1]

array([2, 5, 8])

In [240]:
arr = np.arange(10,30).reshape((4,5))
arr

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [241]:
arr = np.array([[10, 11,12,13,14],[15,16,17,18,19],[20,21,22,23,24], [25,26,27,28,29]])
arr 

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [242]:
arr[1:,2:4]

array([[17, 18],
       [22, 23],
       [27, 28]])

In [243]:
a = np.array([10,20,30,40])
b = np.array([5,5,5,5])
a

array([10, 20, 30, 40])

In [244]:
b

array([5, 5, 5, 5])

In [245]:
np.add(a,b)

array([15, 25, 35, 45])

In [246]:
np.subtract(a,b)

array([ 5, 15, 25, 35])

In [247]:
np.multiply(a,b)

array([ 50, 100, 150, 200])

In [248]:
np.sqrt(a)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532])

In [249]:
np.power(a,b)

array([   100000,   3200000,  24300000, 102400000], dtype=int32)

In [250]:
np.exp(a)

array([2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 2.35385267e+17])

In [251]:
# Quiz
np.array([])  #converts to array

array([], dtype=float64)

In [252]:
np.arange(3,11,2)  # 2 represents steps

array([3, 5, 7, 9])

In [253]:
np.arange(3,11,1)

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [254]:
np.arange(3,11) == np.arange(3,11,1)

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [255]:
np.arange(2,11).reshape(3,3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [256]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [257]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [258]:
arr = np.random.randint(0,1001, 50)

In [259]:
np.reshape(arr, (10,5))

array([[749,  56, 551, 768, 243],
       [748, 637, 346, 650, 557],
       [982, 367, 350, 825, 100],
       [584, 178, 440, 427, 731],
       [141, 429, 903, 613, 896],
       [572, 266, 807, 309, 942],
       [934, 347, 381, 571, 990],
       [603, 533, 668, 901, 214],
       [630, 346, 535, 242, 463],
       [833, 412, 812, 218, 984]])